version: '3.1'
services:
  db:
    container_name: 'db'
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification_system
    ports:
      - "9090:3306"
    volumes:
      - ${PWD}/db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  node:
    container_name: 'app'
    build:
      context: .
      dockerfile: 'Dockerfile'
    user: "node"
    volumes:
      - ./:/home/node/app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306

