version: '3.1'
services:
  db:
    container_name: 'db'
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification_system
    ports:
      - "9090:3306"
    volumes:
      - ./.db/seed.sql:/docker-entrypoint-initdb.d/seed.sql

  producer:
    container_name: 'producer'
    build:
      context: ./producer
    user: "node"
    ports:
      - "8081:8081"
    depends_on:
      - db
      - rabbitmq
    environment:
      WAIT_HOSTS: db:3306

  consumer:
    container_name: 'consumer'
    build:
      context: ./consumer
    user: "node"
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: 'rabbitmq'
    image: "rabbitmq:3-management"
    ports:
      - 5672:5672
      - 15672:15672


